const TEMPLATES = [
  'Good to see you, {name}.',
  'Welcome back, {name}.',
  "Let's make today count, {name}.",
  'Hey {name}, ready to go?',
  'Morning, {name}. What are we tackling today?',
  'Good to have you back, {name}.',
  '{name} is in the building.',
  'Hey {name}. You got this.',
  'Another day, another win. Hi {name}.',
  'Welcome, {name}. Let the day begin.',
  'Back at it, {name}.',
  '{name}, let\'s get to work.',
  'Hey {name}, the grind awaits.',
  'Ready when you are, {name}.',
  '{name} showing up. That\'s the first win.',
  'What\'s the plan, {name}?',
  'Good timing, {name}. Let\'s move.',
  '{name}, today\'s yours.',
  'Oh, it\'s {name}. We\'re saved.',
  '{name} has entered the chat. Everyone relax.',
  'Ah, {name}. Just the human we needed.',
  'Warning: {name} is now online. Productivity incoming.',
  '{name}! The legend returns.',
  'Finally, {name}. We were starting to worry.',
  'The algorithm predicted you\'d show up, {name}. It was right.',
  'Loading {name}... done. Let\'s go.',
  '{name} has logged on. The simulation continues.',
  'They said you wouldn\'t come back, {name}. They were wrong.',
  'ALERT: {name} detected. Deploying tasks.',
  'Welcome back, {name}. Your desk missed you.',
  '{name}. You. Here. Now. Let\'s go.',
  'The coffee is hot and so is your potential, {name}.',
  'Rumour has it {name} gets things done. Prove it.',
  'No pressure, {name}, but everything depends on you today.',
  'The prophecy spoke of {name}. That day is today.',
  'Scientists baffled as {name} logs in again. More at 11.',
  'We\'ve been expecting you, {name}.',
  '{name} online. The void acknowledges you.',
  'Another timeline, another {name}. Hi.',
  'Oh good, {name} is here. Now we can begin the ritual.',
  'The servers warmed up the moment they sensed you, {name}.',
  '{name}. Remarkable. You found the login button again.',
  'Day one of {name} pretending to be productive. Let\'s go.',
  'Hi {name}. Please ignore the previous greeting.',
  'Your enemies are already working, {name}. Just saying.',
];

export function pickGreeting(name: string): string {
  const idx = Math.floor(Math.random() * TEMPLATES.length);
  return TEMPLATES[idx].replaceAll('{name}', name || 'there');
}
